/robot_news_station_giskard:
  ros__parameters:
    robot_name: giskard
    time_period: 2.0

/robot_news_station_bb8:
  ros__parameters:
    robot_name: bb8
    time_period: 2.0

/robot_news_station_daneel:
  ros__parameters:
    robot_name: daneel
    time_period: 2.0

/robot_news_station_jander:
  ros__parameters:
    robot_name: jander
    time_period: 2.0

/robot_news_station_c3po:
  ros__parameters:
    robot_name: c3po
    time_period: 2.0